import '../../api/persons/methods.js';
import '../../api/persons/server/publications.js';
import '../../api/organizations/methods.js';
import '../../api/organizations/server/publications.js';
import '../../api/stats/methods.js';
import '../../api/tmp/server/publications.js';
import '../../api/tmp/methods.js';
import '../../api/stats/server/publications.js';
import '../../api/parse/methods.js';
import '../../api/server/version.js';
import '../../api/mail.js';
import '../../api/images/server/publications.js';
import '../../api/contracts/server/publications.js';
import '../../api/contracts_ocds/server/publications.js';
import '../../api/contracts/methods';
import '../../api/matches/methods.js';
import '../../api/revisions/server/publications.js';
import '../../api/users/server/publications.js';
import '../../api/users/methods.js';
import '../../api/collectionHooks.js';
import '../../api/memberships/server/publications.js';
// FIXME enable following further testing of membership updates
// import '../../api/memberships/methods.js';
