import { reduce, extend } from 'lodash';
import SimpleSchema from 'simpl-schema';

const cargoCsvHeaders = [
  'Apellido',
  'Nombre',
  'sexo',
  'cargoTipo',
  'cargoClase',
  'cargoNominal',
  'Organizacion',
  'parentOrg',
  'duracionCargo',
  'territorio',
  'territorioExtendido',
  'fechaNombramiento',
  'fechaInicioYear',
  'fechaInicio',
  'fuenteDeDatosInicio',
  'urlFuenteInicio',
  'calidadDelDatoInicio',
  'fechaFinYear',
  'fechaFin',
  'fuenteDeDatosFin',
  'urlFuenteFin',
  'calidadDelDatoFin',
  'partido',
  'partidoGeneral',
  'documentoTipo',
  'nroDeDoc',
  'urlFoto',
  'areaId',
  'patrimTotal',
  'patrimUrl',
  'nacimiento',
  'muerte',
  'Observaciones',
  'agregadoPor',
].map((s) => {
  const obj = {};
  obj[s] = { type: String };
  return obj;
});

export const cargografiasSchema =
new SimpleSchema(reduce(cargoCsvHeaders, (sch, ele) => (extend(sch, ele))));

const NAICMCsvHeaders = [
  'CONTRACT_ID_STRING',
  'CONTRACT_TITLE_STRING',
  'CONTRACT_NUM_PROC_STRING',
  'CONTRACT_DEPENDENCY_STRING',
  'CONTRACT_TYPE_PROC_STRING',
  'CONTRACT_TYPE_STRING',
  'CONTRACT_REFERENCES_STRING',
  'CONTRACT_PROVIDER_ORG_STRING',
  'ORG_NAME_STRING',
  'ORG_SUBORGS_ARRAY',
  'ORG_PARENT_IMMEDIATE_STRING',
  'ORG_PARENT_ARRAY',
  'ORG_OTHER_NAMES_ARRAY',
  'ORG_INITIALS_STRING',
  'CONTRACT_PROVIDER_PERSON_STRING',
  'CONTRACT_AMOUNT_STRING',
  'ORG_COUNTRY_STRING',
  'ORG_STATE_STRING',
  'ORG_CITY_STRING',
  'ORG_ZONE_STRING',
  'ORG_STREET_STRING',
  'ORG_ZIPCODE_STRING',
  'ORG_PHONES_ARRAY',
  'ORG_WEBSITE_STRING',
  'ORG_EMAILS_ARRAY',
  'ORG_FOUNDATION_YEAR_STRING',
  'ORG_SHAREHOLDERS_ARRAY',
  'ORG_SHAREHOLDERS_SHARES_ARRAY',
  'ORG_SHAREHOLDERS_PERSONS_ARRAY',
  'ORG_SHAREHOLDERS_PERSONS_SHARES_ARRAY',
  'ORG_LENDERS_ARRAY',
  'ORG_INVESTMENTS_ARRAY',
  'ORG_INVESTMENTS_PERCENT_ARRAY',
  'ORG_PUBLIC_STRING',
  'ORG_BOARD_ARRAY',
  'ORG_BOARD_ROLE_ARRAY',
  'ORG_PROFESSIONAL_ARRAY',
  'ORG_PROFESSIONAL_ROLE_ARRAY',
  'ORG_EMPLOYEES_STRING',
  'ORG_REFERENCES_ARRAY',
  'PERSON_ID_STRING',
  'PERSON_NAME_STRING',
  'PERSON_PREFIX_ARRAY',
  'PERSON_SUFFIX_ARRAY',
  'PERSON_GENDER_STRING',
  'PERSON_COUNTRY_ARRAY',
  'PERSON_BOARD_ARRAY',
  'PERSON_BOARD_ROLE_ARRAY',
  'PERSON_PUBLIC_ARRAY',
  'PERSON_PUBLIC_ROLE_ARRAY',
  'PERSON_PUBLIC_DEPARTMENT_ARRAY',
  'PERSON_BOARD_START_DATE_ARRAY',
  'PERSON_BOARD_END_DATE_ARRAY',
  'PERSON_PROFESSIONAL_ARRAY',
  'PERSON_PROFESSIONAL_ROLE_ARRAY',
  'PERSON_PROFESSIONAL_START_DATE_ARRAY',
  'PERSON_PROFESSIONAL_END_DATE_ARRAY',
  'PERSON_SHAREHOLDER_ARRAY',
  'PERSON_SHAREHOLDER_SHARES_ARRAY',
  'PERSON_SHAREHOLDER_START_DATE_ARRAY',
  'PERSON_SHAREHOLDER_END_DATE_ARRAY',
  'PERSON_REFERENCES_ARRAY',
].map((s) => {
  const obj = {};
  obj[s] = { type: String, optional: true };
  return obj;
});

export const NAICMSchema = new SimpleSchema(reduce(NAICMCsvHeaders, (sch, ele) => (extend(sch, ele))));
